# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84079f3880aa81c1f9234bdaca7446a8ad975ef0861eacb9953907dc1f009a00f58b5c5df4892894a4795d5a0de3b456c35b18bbf042fbc59c9dbddc358adce8

test:
  secret_key_base: 151911bebc0b8fcd42d452f415d24130c7b50aff9434d7030f74896bbbdcf01a68134d2db8ab08578cff122bf58353e5dbc2dc08ac546db0c549a33e53cef0e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
